GET http://localhost:8080/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmFubmEiLCJpYXQiOjE3NzEyNjIxNzMsImV4cCI6MTc3MTI2MjE5M30.WmIwo80w4vJa_xWFG0_hOIJso_U-utzc9jNJPpg1ZsY
###

POST http://localhost:8080/token
Content-Type: application/json
{
    "token" : ""
}
###

POST http://localhost:8080/login
Content-Type:  application/json

{
    "username": "Nanna"
}