### Health Check
GET http://localhost:8080/health

### Checking JWKS endpoint
GET http://localhost:8080/.well-known/jwks.json

### Check key status
GET http://localhost:8080/key-status


### Authentication
### 1. Login first - get token and refresh token
POST http://localhost:8080/login
Content-Type:  application/json

{
    "username": "Nanna"
}

### 2. Obtaining posts with token
GET http://localhost:8080/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImtleS0yMDI2LTAyLTIxLTJkMjA3NTliIn0.eyJuYW1lIjoiTmFubmEiLCJpYXQiOjE3NzE2OTcxNDgsImV4cCI6MTc3MTY5NzE2OH0.rc-csgNDnznuHpY0-Yt04wxPpNIl8kq4vJ5xuhK7gwA

### Verifying key status
POST http://localhost:8080/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmFubmEiLCJpYXQiOjE3NzE2OTcxMzl9.2JZkMzrcDbfdfr4qQft5yXXF62hXIf4ipTAw8EpNnJQ"
}

####################
### Check key status
GET http://localhost:8080/key-status

### Maintenance
POST http://localhost:8080/rotate-keys
Content-Type: application/json

{
    "expiresInDays": 1
}